---
title: 'PSC 632: Democratization'
author: 'Instructor: Dr. Amanda B. Edgell (abedgell@ua.edu)'
date: "Fall 2023"
output:
  html_document:
    toc: yes
    toc_float: yes
subtitle: "Tuesdays, 1:00-3:30pm"
filename: schedule.Rmd 
---

```{css, echo=FALSE}
p {
  font-size: 16px;
}

td {
  font-size: 16px;
}

ul li{
 font-size:16px;
}

ol li{
 font-size:16px;
}
```

**Office Hours:** 314 TH, Tuesdays, 3:45-4:45pm

**Last Updated:** `r format(Sys.time(), '%d %B, %Y')`

--- 


# Course Schedule {#schedule}

Generally, I recommend reading the materials in the order listed on the course schedule below. For books, unless the entire text is assigned (see [Required Texts](index.html#texts)), you will be able to access the assigned pages from the link. For articles, I have provided the DOI link, which should allow you to access the text free of charge when on the UA network. Otherwise, you should be able to locate them through Google Scholar or the UA library. 

</br>


## 29 August 2023 

**Topic: Course Introduction and Waves**

Today we will cover the particulars of the course, review the syllabus, and have our first discussion covering the assigned readings below. Even though this is our first class - you are expected to submit discussion questions and come prepared to discuss the material.

**Required Reading:**

* Huntington, Samuel P. 1993. *The Third Wave: Democratization in the Late Twentieth Century*. Norman, OK: University of Oklahoma  Press, 3-30. https://alabama.box.com/s/dxs88z9t5az8gd1yhn8t51ch4hcqgaw2 
* Lührmann, Anna and Staffan I. Lindberg. 2017. "A Third Wave of Autocratization is Here: What is New About it?" *Democratization* 26, no. 7: 1095-1113. https://doi.org/10.1080/13510347.2019.1582029
* *Why Democracies Develop and Decline*, Chapters 1-2, 1-54

</br>

## 05 September 2023

**Topic: Current Controversies**

This week we will cover two ongoing controversies in the literature on democratization -- (1) whether we really see waves of regime transformation throughout history and (2) whether the world is currently experiencing democratic backsliding. 

**Required Reading:**:

* Skaaning, Svend-Erik. 2020. "Waves of Autocratization and Democratization: A Critical Note on Conceptualization and Measurement." *Democratization* 27, no. 8: 1533-1542. https://doi.org/10.1080/13510347.2020.1799194
* Tomini, Luca. 2021. "Don't Think Like a Wave! A Research Note About the Current Autocratization Debate." *Democratization* 28, no. 6: 1191-1201. https://doi.org/10.1080/13510347.2021.1874933 
* Boese, Vanessa A., Staffan I. Lindberg, and Anna Lührmann. 2021. "Waves of Autocratization and Democratization: A Rejoinder." *Democratization* 28, no. 6: 1202-1210. https://doi.org/10.1080/13510347.2021.1923006 
* Little, Andrew and Anne Meng. 2023. "Subjective and Objective Measurement of Democratic Backsliding." http://dx.doi.org/10.2139/ssrn.4327307
* Knutsen, Carl Henrik, et al. 2023. "Conceptual and Measurement Issues in Assessing Democratic Backsliding." V-Dem Working Paper Series, 140.  http://dx.doi.org/10.2139/ssrn.4494175

</br>

## 12 September 2023

**Topic: More Conceptualization  and Measurement**

This week we will continue discussing the debates over how to properly conceptualize and measure democracy and democratization.

**Required Reading:**

* Schumpeter, Joseph. 2003. "Capitalism, Socialism, and Democracy" in *The Democracy Sourcebook* edited by Robert A. Dahl, Ian Shapiro, and Jose Antonio Cheibub, 5--11. Cambridge, MA: MIT Press. https://alabama.box.com/s/bezcmw7c47f2m0vv0cg3i8m67oumfxl3 
* Dahl, Robert A. 1971. *Polyarchy: Participation and Opposition*. New Haven: Yale University Press,  1-16. https://alabama.box.com/s/ylaerdd0m2n7mahnt2sko3txa66ou53j 
* Przeworski, Adam. 2003. "Minimalist Conception of Democracy: A Defense" in *The Democracy Sourcebook* edited by Robert A. Dahl, Ian Shapiro, and Jose Antonio Cheibub, 12-17. Cambridge, MA: MIT Press. https://alabama.box.com/s/cdmrguq47zg3dde5hn3e9hfbxnhkl137 
* Munck, Gerardo L. and Jay Verkuilen. 2002. "Conceptualizing and Measuring Democracy." *Comparative Political Studies* 35, no. 1: 5-34. https://doi.org/10.1177/001041400203500101. 
* Coppedge, Michael, et al. 2011. "Conceptualizing and Measuring Democracy: A New Approach." *Perspectives on Politics* 9, no. 2: 247-267. https://doi.org/10.1017/S1537592711000880 
* Lueders, Hans and Ellen Lust. 2018. "Multiple Measurements, Elusive Agreement, and Unstable Outcomes in the Study of Regime Change." *Journal of Politics* 80, no. 2: 736-741. http://dx.doi.org/10.1086/696864. 
* Maerz, Seraphine F., Amanda B. Edgell, Matthew C. Wilson, Sebastian Hellemeier, and Staffan I. Lindberg. 2023. "Episodes of Regime Transformation." *Journal of Peace Research*, 1-18. (This article has been in production for 5 months! Will share the link once it is available.)

*Recommended Reading*: 

* Coppedge, Michael. 2012. *Democratization and Research Methods*. New York: Cambridge University Press.
* Munck, Gerardo L. 2009. *Measuring Democracy: A Bridge Between Scholarship & Politics.* Baltimore, MD: Johns Hopkins University Press. 
* Linz, Juan J. 2000. *Totalitarian and Authoritarian Regimes* Boulder, CO: Lynne Rienner Publishers. 

</br>

## 19 September 2023

**Topic: Problems of Democratic Transition ** 

This week we'll read a substantial portion of the book *Problems of Democratic Transition and Consolidation* by Juan J. Linz and Alfred Stepan. In addition to reading the first part of the book, which sets up their theory, you will be assigned to read one of the case study chapters. During our discussion, you will inform the rest of the class about your case and how it fits within the theory. In addition, you should research how your case has fared since the publication of Linz and Stepan. Has it “consolidated” as a democracy? Did it “backslide” into authoritarianism?


**Required Reading:**

* Linz, Juan J. and Alfred Stepan. 1996. *Problems of Democratic Transition and Consolidation: Southern Europe, South America, and Post-Communist Europe.* Baltimore, MD: Johns Hopkins University Press, 3-83 + selected chapter(s) on cases.

*Recommended Reading:*

* O'Donnell, Guillermo and Philippe C. Schmitter. 1986. *Transitions from Authoritarian Rule: Tentative Conclusions about Uncertain Democracies.* Baltimore, MD: Johns Hopkins University Press. 

</br>

##  26 September 2023 

**Topic: European and Protestant with Natural Harbors?**

This week, we'll delve into the debates over European exceptionalism and whether Protestantism or natural harbors (or neither) explains the progression of modern democracy in Europe.  

**Required Reading:**

* *Why Democracies Develop and Decline*, Chapter 3, 55-79.
* Gerring, John, Brendan Apfeld, Tore Wig, and Andreas Forø Tollefsen. 2022. *The Deep Roots of Modern Democracy: Geography and the Diffusion of Political Institutions*. New York: Cambridge University Press. 

*Recommended Reading:*

* Webber, Max. 1930. *The Protestant Ethic and the Spirit of Capitalism* London: George Allen and Unwin Ltd. 
* Mamdani, Mahmood. 1996. *Citizen and Subject: Contemporary Africa and the Legacy of Late Colonialism.* Princeton, N.J.: Princeton University Press. 
* French, Howard. 2021. *Born in Blackness: Africa, Africans, and the Making of the Modern World, 1471 to the Second World War.* New York: W.W. Norton. 

</br>

## 03 October 2023

**Exam Track:** We will have a practice exam during this class period. The exam will cover material from Weeks 1-5. 

**Project Track:** You must submit a 1-2 page summary of your proposed paper project. You should bring a printed copy of your project summary to our classroom on Tuesday, 03 October between 1-3:30pm.

</br>

## 10 October 2023 

**Topic: "Modernization" Theory**

Does development cause democratization? Are there long-run processes of human *evolution* that eventually lead from traditional societies to modern, democratic, and capitalistic ones? This week we evaluate the “modernization” theory, assessing the evidence for and against its claims. Afterward, we will discuss the political factors that gave rise to this theory and why it “never dies.”


**Required Reading:**

* Lipset, Seymour Martin. 1959. "Some Social Requisites of Democracy: Economic Development and Political Legitimacy." *American Political Science Review* 53, no. 1: 69--105. https://doi.org/10.2307/1951731.
* Przeworski, Adam and Fernando Limongi. 1997. "Modernization: Theories and Facts." *World Politics* 49, no. 2: 155--183. https://www.jstor.org/stable/25053996. 
* Boix, Carles and Susan Stokes. 2003. "Endogenous Democratization." *World Politics* 55, no. 4: 517--549. https://www.jstor.org/stable/25054237. 
* *Why Democracies Develop and Decline*, Chapter 5, 119-160
* Gilman, Nils. 2018. "Modernization Theory Never Dies." *History of Political Economy" 50, no. S1: 133--151. https://doi.org/10.1215/00182702-7033896. 
* Munck, Gerardo. 2018. "Modernization Theory as a Case of Failed Knowledge Production." *Annals of Comparative Democratization* 16, no. 3: 37--41. 
https://connect.apsanet.org/s35/wp-content/uploads/sites/26/2018/10/2018_16_3-Annals_of_CD_September.pdf 

*Recommended Reading:*

* Wucherpfennig, Julian and Franziska Deutsch. 2009. "Modernization and Democracy: Theories and Evidence Revisited." *Living Reviews in Democracy*: 1--9. http://www.livingreviews.org/lrd-2009-4. 
* Moore, Barrington. 1966. *Social Origins of Dictatorship and Democracy: Lord, Peasant, and the Making of the Modern World.* Boston: Beacon Press. 
* Rueshemeyer, Dietrich, Evelyne Huber Stephens, and John D. Stephes. 1992. *Capitalist Development and Democracy.* Chicago: University of Chicago Press.
* Gilman, Nils. 2007. *Mandarins of the Future: Modernization Theory in Cold War America.* Baltimore, MD: Johns Hopkins University Press.

</br>

## 17 October 2023 

**Topic: International Dimensions**

This one's for the IR students in the course, but also a reminder to CP that foreign actors and global events often shape the domestic context. We will explore several different international dimensions of democratization, including foreign pressure, material incentives, and diffusion. 


**Required Reading:**

* Brinks, Daniel and Michael Coppedge. 2006. "Diffusion is No Illusion: Neighbor Emulation in the Third Wave of Democratization" *Comparative Political Studies* 39, no. 4: 463-489. 
https://doi.org/10.1177/0010414005276666. 
* *Why Democracies Develop and Decline*, Chapter 4, 80-118.
* Goldring, Edward and Sheena Chestnut Greitens. 2020. "Rethinking Democratic Diffusion: Bringing Regime Type Back In." *Comparative Political Studies* 53, no. 2: 319--353. https://doi.org/10.1177/0010414019852701. 
* Levitsky, Stephen and Lucan Way. 2006. "Linkage versus Leverage: Rethinking the International Dimension of Regime Change." *Comparative Politics* 38, no. 4: 379--400. https://doi.org/10.2307/20434008. 
* Wright, Joseph. 2009. "How Foreign Aid Can Foster Democratization in Authoritarian Regimes." *American Journal of Political Science* 53, no. 3: 552-571. https://doi.org/10.1111/j.1540-5907.2009.00386.x. 
* Clarke, Killian. 2023. "Ambivalent Allies: How Inconsistent Foreign Support Dooms New Democracies." *Journal of Peace Research* 60, no. 1: 157-171. https://doi.org/10.1177/00223433221137612. 


*Recommended Reading:*

* Levitsky, Steven and Lucan A. Way. 2010. *Competitive Authoritarianism: Hybrid Regimes after the Cold War.* New York: Cambridge University Press. 
* Bush, Sarah Sunn. 2015. *The Taming of Democracy Assistance: Why Democracy Promotion Does Not Confront Dictators.* New York: Cambridge University Press. 
* Downes, Alexander B. and Jonathan Monten. 2013. "Forced to be Free? Why Foreign-imposed Regime Change Rarely Leads to Democratization." *International Security* 47, no. 4: 90-131. https://doi.org/10.1162/ISEC_a_00117. 

</br>

## 24 October 2023 

**Topic: Institutional Dimensions**

Institutions and their legacies play an essential role in the literature on democratization. This week we look at some of the institutions under authoritarianism – such as elections, parties, and legislatures – and the overall organization of the regime to evaluate whether these matter and whether they help or hinder democratization.

**Required Reading:**

* Geddes, Barbara. 1999. "What Do We Know About Democratization After Twenty Years?" *Annual Review of Political Science* 2: 115-144. https://doi.org/10.1146/annurev.polisci.2.1.115.  
* Frantz, Erica and Andrea Kendall-Taylor. 2016. "Pathways to Democratization in Personalist Dictatorships." *Democratization* 24, no. 1: 20-40. https://doi.org/10.1080/13510347.2015.1131977. 
* Gandhi, Jennifer and Adam Przeworski. 2007. "Authoritarian Institutions and the Survival of Autocrats." *Comparative Political Studies* 40, no. 11: 1279--1301. https://doi.org/10.1177/0010414007305817. 
* Wright, Joseph and Abel Escribá-Folch. 2012. "Authoritarian Institutions and Regime Survival: Transitions to Democracy and Subsequent Autocracy." *British Journal of Political Science* 42, no. 2: 283--309. https://doi.org/10.1017/S0007123411000317. 
* Edgell, Amanda B., Valeriya Mechkova, David Altman, Michael Bernhard, and Staffan I. Lindberg. 2018. "When and Where do Elections Matter: A Global Test of the Democratization by Elections Hypothesis, 1900-2010." *Democratization* 25, no. 3: 422--444. https://doi.org/10.1080/13510347.2017.1369964. 
* Donno, Daniela. 2013. "Elections and Democratization in Authoritarian Regimes." *American Journal of Political Science* 57, no. 3: 703--716. https://doi.org/10.1111/ajps.12013. 


*Recommended Reading:*

* Geddes, Barbara, Joseph Wright, and Erica Frantz. 2014. "Autocratic Breakdown and Regime Transitions: A New Data Set." *Perspectives on Politics* 12, no. 2: 313-331. https://doi.org/10.1017/S1537592714000851. 
* *Why Democracies Develop and Decline*, Chapter 6, 163-184.
* Gandhi, Jennifer. 2008. *Political Institutions Under Dictatorship.* New York: Cambridge University Press. 
* Ghandi, Jennifer and Ellen Lust-Okar. 2009. "Elections Under Authoritarianism." *Annual Review of Political Science* 12: 403-422. https://doi.org/10.1146/annurev.polisci.11.060106.095434. 
* Lindberg, Staffan I. ed. 2009. *Democratization by Elections: A New Mode of Transition.* Baltimore, MD: Johns Hopkins University Press. 
* Levitsky, Stephen and Lucan Ahmed Way. 2020. "The New Competitive Authoritarianism." *Journal of Democracy* 31, no. 1: 51-65.  https://doi.org/10.1353/jod.2020.0004 

</br>

## 31 October 2023

**Topic: Power to the People!**

Can ordinary citizens encourage democratization through their mobilization? What types of civil resistance are more or less likely to be successful and result in democracy? This week we look at these questions and evaluate the revolutionary potential of the masses. 

**Required Reading:**

* Chenoweth, Erica and Maria J. Stephan. 2011. *Why Civil Resistance Works: The Strategic Logic of Nonviolent Conflict* New York: Columbia University Press.
* *Why Democracies Develop and Decline*, Chapter 7, 185-214.

*Recommended Reading:*

* Putnam, Robert D. 1993. *Making Democracy Work: Civic Traditions in Modern Italy.* Princeton, N.J.: Princeton University Press. 
* Dahlum, Sirianne. 2023. "Joining Forces: Social Coalitions and Democratic Revolutions." *Journal of Peace Research* 60, no. 1: 42-57. https://doi.org/10.1177/00223433221138614. 
* Hellmeier, Sebastian and Michael Bernhard. 2023. "Regime Transformation from Below: Mobilization for Democracy and Autocracy from 1900 to 2021." *Comparative Political Studies*, 1-33. https://doi.org/10.1177/00104140231152793. 

</br>

## 07 November 2023 

**Topic: Bringing it Together**

This week, we will consider a metatheory of democratization primarily influenced by structural factors. We’ll then compare this argument to recent claims that democratization might be a “mistake.” As we discuss these works, we should carefully consider how they fit within the other readings throughout the course to draw some general conclusions about what we know about democratization after over 60 years of empirical research.

**Required Reading:** 

* *Why Democracies Develop and Decline*, Chapter 8, 214-261.
* Treisman, Daniel. 2020. "Democracy by Mistake: How Errors of Autocrats Trigger Transitions to Freer Government." *American Political Science Review* 114, no. 3: 792--810. https://doi.org/10.1017/S0003055420000180

</br>

## 14 November 2023

**Topic: Democracy in Hard Places?**

What makes democracy most likely to emerge and endure? Throughout the semester, we’ve focused on several factors that facilitate democratization. This week we investigate several cases where democracy has thrived despite the odds. What makes these cases unique? What can others learn from them?


**Required Reading:** 

* Dorenspleet, Renske, Petr Kopecky, and Cas Mudde (eds.). 2008. *Democratization: Special Issue on Deviant Democracies* 15, no. 4: 695--832. https://www.tandfonline.com/toc/fdem20/15/4 
* Mainwaring, Scott and Tarek Masoud (eds.). 2022. *Democracy in Hard Places*. New York: Oxford University Press. 


</br>

## 28 November 2023 

**Exam Track:** Final exam will take place during our regular class time. 

**Project Track:** If you would like feedback on a draft of your paper, you must submit it to me by 3:30pm on 14 November, both as a hard copy and emailed soft copy.

</br>


## 11 December 2023 (10:30am) 

**Exam Track:** You can retake the final exam on 11 December 2023, 10:30am–12:30pm. 

**Project Track:** Final projects should be submitted as a hard copy to my mailbox and a soft copy to my email by 12:30pm on 11 December 2023.

---
