---
title: "PSC 632: Democratization"
subtitle: "Tuesdays, 1:00-3:30pm"
author: "Amanda B. Edgell, Assistant Professor, University of Alabama"
date: "Fall 2023"
output: 
  html_document:
   toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Required Texts:

* Coppedge, Michael, Amanda B. Edgell, Carl Henrik Knutsen, and Staffan I. Lindberg, eds. 2022. *Why Democracies Develop and Decline*. New York: Cambridge University Press.
*  O'Donnell, Guillermo and Philippe C. Schmitter. 1986. *Transitions from Authoritarian Rule: Tentative Conclusions about Uncertain Democracies.* Baltimore, MD: Johns Hopkins University Press. 
* Gerring, John, Brendan Apfeld, Tore Wig, and Andreas Forø Tollefsen. 2022. *The Deep Roots of Modern Democracy: Geography and the Diffusion of Political Institutions*. New York: Cambridge University Press. 
* Chenoweth, Erica and Maria J. Stephan. 2011. *Why Civil Resistance Works: The Strategic Logic of Nonviolent Conflict* New York: Columbia University Press.


# Course Schedule

Generally, I recommend that you read these in the order listed. You are expected to have completed the readings *before* class and come prepared with discussion points and questions. For this to be effective, you should *critically* engage with the readings, i.e. read actively rather than passively. Consider how the readings connect, build upon, or debate one another. Develop you own viewpoint and come prepared to have it challenged by other students in the class. 

## Week 1 - Introduction
*29 August 2023*

### Required Reading
* Syllabus
* Huntington, Samuel P. 1993. *The Third Wave: Democratization in the Late Twentieth Century*. Norman, OK: University of Okalhoma Press, 3--30.
* Lührmann, Anna and Staffan I. Lindberg. 2017. "A Third Wave of Autocratization is Here: What is New About it?" *Democratization* 26, no. 7: 1095-1113.
* *Why Democracies Develop and Decline*, Chapters 1-2, X--X

## Week 2 - 
*05 September 2023* 

### Required Reading
* Skaaning, Svend-Erik. 2020. "Waves of Autocratization and Democratization: A Critical Note on Conceptualization and Measurement." *Democratization* 27, no. 8: 1533--1542. 
* Tomini, Luca. 2021. "Don't Think Like a Wave! A Research Note About the Current Autocratization Debate." *Democratization* 28, no. 6: 1191-1201. 
* Boese, Vanessa A., Staffan I. Lindberg, and Anna Lührmann. 2021. "Waves of Autocratization and Democratization: A Rejoinder." *Democratization* 28, no. 6: 1202-1210. 


## Week 3 - More Conceputalization and Measurement  
*12 September 2023*


### Required Reading
* Schumpeter, Joseph. 2003. "Capitalism, Socialism, and Democracy" in *The Democracy Sourcebook* edited by Robert A. Dahl, Ian Shapiro, and Jose Antonio Cheibub, 5--11. Cambridge, MA: MIT Press. 
* Dahl, Robert A. 1971. *Polyarchy: Participation and Opposition*. New Haven: Yale University Press,  1--16.
* Przeworski, Adam. 2003. "Minimalist Conception of Democracy: A Defense" in *The Democracy Sourcebook* edited by Robert A. Dahl, Ian Shapiro, and Jose Antonio Cheibub, 12--17. Cambridge, MA: MIT Press. 
* Coppedge, Michael. 2012. *Democratization and Research Methods*. New York: Cambridge University Press, 11--48. 
* Maerz, Seraphine F., Amanda B. Edgell, Matthew C. Wilson, Sebastian Hellemeier, and Staffan I. Lindberg. 2023. "Episodes of Regime Transformation." *Journal of Peace Research*, 1--18.

## Week 4 - Two Modern Classics 
*19 September 2023*

### Required Reading:
* O'Donnell, Guillermo and Philippe C. Schmitter. 1986. *Transitions from Authoritarian Rule: Tentative Conclusions about Uncertain Democracies.* Baltimore, MD: Johns Hopkins University Press. 
* Linz, Juan J. and Alfred Stepan. 1996. *Problems of Democratic Transition and Consolidation: Southern Europe, South America, and Post-Communist Europe.* Baltimore, MD: Johns Hopkins University Press, 3--83. 


##  Week 5 - European and Protestant with Natural Harbors?
*26 September 2023*

### Required Reading
* *Why Democracies Develop and Decline*, Chapter 3, X-X
* Gerring, John, Brendan Apfeld, Tore Wig, and Andreas Forø Tollefsen. 2022. *The Deep Roots of Modern Democracy: Geography and the Diffusion of Political Institutions*. New York: Cambridge University Press. 



## Week 6 - "Modernization" Theory
*03 October 2023*

### Required Reading
* Lipset, Seymour Martin. 1959. "Some Social Requisites of Democracy: Economic Development and Political Legitimacy." *American Political Science Review* 53, no. 1: 69--105. 
* Przeworski, Adam and Fernando Limongi. 1997. "Modernization: Theories and Facts." *World Politics* 49, no. 2: 155--183. 
* Boix, Carles and Susan Stokes. 2003. "Endogenous Democratization." *World Politics* 55, no. 4: 517--549. 
* *Why Democracies Develop and Decline*, Chapter 5, X-X
* Fritzsche, Erik and A. Vogler. 2020. "Why the Confusion? Reasons and Remedies for Shortcomings and Progress in Modernization Theory." *Democratization* 27, no. 7: 1261--1279.
* Gilman, Nils. 2018. "Modernization Theory Never Dies." *History of Political Economy" 50, no. S1: 133--151.

### Recommended Reading: 
* Wucherpfennig, Julian and Franziska Deutsch. 2009. "Modernization and Democracy: Theories and Evidence Revisited." *Living Reviews in Democracy*: 1--9.
* Moore, Barrington. 1966. *Social Origins of Dictatorship and Democracy: Lord, Peasant, and the Making of the Modern World.* Boston: Beacon Press. 
* Gilman, Nils. 2007. *Mandarins of the Future: Modernization Theory in Cold War America.* Baltimore, MD: Johns Hopkins University Press.

## Week 7 - International Dimensions 
*10 October 2023* 

### Required Reading
* Levitsky, Stephen and Lucan Way. 2006. "Linkage versus Leverage: Rethinking the International Dimension of Regime Change." *Comparative Politics* 38, no. 4: 379--400. 
* Finkel, Steven E., Anibál Pérez-Liñán, and Mitchell A. Seligson. 2011. "The Effects of U.S. Foreign Assistance on Democracy Building, 1990-2003." *World Politics* 59, no.3: 404--439. 
* Finkel, Steven E., Anibál Pérez-Liñán, Michael Neureiter, and Chris A. Belasco. 2020. "Effects of US Foreign Assistance on Democracy Building, 1990-2014: An Update." *Kellogg Institute Working Paper*, no. 436: 1--36. 
* *Why Democracies Develop and Decline*, Chapter 4, X-X
* Goldring, Edward and Sheena Chestnut Greitens. 2020. "Rethinking Democratic Diffusion: Bringing Regime Type Back In." *Comparative Political Studies* 53, no. 2: 319--353. 

### Recommended Reading: 
* Levitsky, Steven and Lucan A. Way. 2010. *Competitive Authoritarianism: Hybrid Regimes after the Cold War.* New York: Cambridge University Press. 
* Escribá-Folch, Abel, Covadonga Meseguer, and Joseph Wright. 2015. "Remittances and Democratization." *International Studies Quarterly* 59: 571--586. 
* Bush, Sarah Sunn. 2015. *The Taming of Democracy Assistance: Why Democracy Promotion Does Not Confront Dictators.* New York: Cambridge University Press. 


## Week 8 - Institutions 
*17 October 2023*

### Required Reading
* *Why Democracies Develop and Decline*, Chapter 6, X-X
* Gandhi, Jennifer and Adam Przeworski. 2007. "Authoritarian Institutions and the Survival of Autocrats." *Comparative Political Studies* 40, no. 11: 1279--1301. 
* Wright, Joseph and Abel Escribá-Folch. 2012. "Authoritarian Institutions and Regime Survival: Transitions to Democracy and Subsequent Autocracy." *British Journal of Political Science* 42, no. 2: 283--309. 
* Edgell, Amanda B., Valeriya Mechkova, David Altman, Michael Bernhard, and Staffan I. Lindberg. 2018. "When and Where do Elections Matter: A Global Test of the Democratization by Elections Hypothesis, 1900-2010." *Democratization* 25, no. 3: 422--444. 
* Donno, Daniela. 2013. "Elections and Democratization in Authoritarian Regimes." *American Journal of Political Science* 57, no. 3: 703--716. 


### Recommended Reading
* Gandhi, Jennifer. 2008. *Political Institutions Under Dictatorship.* New York: Cambridge University Press. 
* Lindberg, Staffan I. ed. 2009. *Democratization by Elections: A New Mode of Transition.* Baltimore, MD: Johns Hopkins University Press. 
* Kavasoglu, Berker. 2022. "Autocratic Ruling Parties During Regime Transitions: Investigating the Democratizing Effect of Strong Ruling Parties." *Party Politics* 28, no. 2: 377--388. 

## Week 9 - Power to the People! 
*24 October 2023*

### Required Reading: 
* Chenoweth, Erica and Maria J. Stephan. 2011. *Why Civil Resistance Works: The Strategic Logic of Nonviolent Conflict* New York: Columbia University Press.
* *Why Democracies Develop and Decline*, Chapter 7, X--X

## Week 10 - Bringing it Together
*31 October 2023*

### Required Reading: 
* *Why Democracies Develop and Decline*, Chapter 8, X--X


## Week 11 - Writing Week/Study Break

## Week 12 - Presentations

## Week 13 - Thanksgiving Break

## Week 14 - Revisions/Study Break  

## Week 15 - Mini-Comprehensive Exam




